vectorstore:
  type: ${VECTORSTORE_TYPE:chroma}      # options: faiss | chroma
  persist_dir: ${FAISS_DIR:./vectorstore/faiss_index}
  chroma_dir: ${CHROMA_DIR:./vectorstore/chroma_index}

embeddings:
  model_name: ${EMBEDDING_MODEL:sentence-transformers/all-MiniLM-L6-v2}

chunking:
  chunk_size: ${CHUNK_SIZE:1000}
  chunk_overlap: ${CHUNK_OVERLAP:150}

retrieval:
  k: ${RETRIEVAL_K:4}

model:
  provider: ${MODEL_PROVIDER:openai}  # openai | ollama | huggingface
  openai:
    model: ${OPENAI_MODEL:gpt-5}
    temperature: ${OPENAI_TEMP:0.2}
  ollama:
    base_url: ${OLLAMA_BASE_URL:http://localhost:11434}
    model: ${OLLAMA_MODEL:llama3}
    temperature: ${OLLAMA_TEMP:0.2}
  huggingface:
    repo_id: ${HF_REPO_ID:mistralai/Mixtral-8x7B-Instruct-v0.1}
    temperature: ${HF_TEMP:0.2}
